#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'..'),FILE=process.env.AT_MANIFEST||path.join(ROOT,'games.json'),ART=path.join(ROOT,'assets/cards/apex-tennis.svg');
const EXPECT={icon:'🎾',title:'Apex Tennis',desc:'Call the point before the serve, then build it on court. A complete offline tennis game with real rules, three rival styles and an honest Plan Rating.',href:'/apextennis/',tag:'Physics',hue:'#3B6FD4',featured:false,hero:false,art:'/assets/cards/apex-tennis.svg',collection:'Sports'};
function rgb(h){return[h.slice(1,3),h.slice(3,5),h.slice(5,7)].map(x=>parseInt(x,16))}function dist(a,b){a=rgb(a);b=rgb(b);return Math.hypot(a[0]-b[0],a[1]-b[1],a[2]-b[2])}
function validate(doc,artText){const errors=[],games=doc.games||[],hits=games.filter(g=>g.title===EXPECT.title||g.href===EXPECT.href);if(games.length!==34)errors.push('count');if(hits.length!==1)errors.push('exactly-once');const g=hits[0]||{};for(const [k,v] of Object.entries(EXPECT))if(g[k]!==v)errors.push('field:'+k);if(!games.every(x=>typeof x.art==='string'&&x.art))errors.push('art-complete');if(new Set(games.map(x=>x.title)).size!==games.length)errors.push('title-unique');if(new Set(games.map(x=>x.href)).size!==games.length)errors.push('href-unique');const sports=games.filter(x=>x.collection==='Sports').map(x=>x.title);if(JSON.stringify(sports)!==JSON.stringify(['Apex Kick','Apex Pool','Apex Golf','Apex Tennis']))errors.push('sports-order');const siblings=['#2F8F6B','#F2A24A','#7C5CFC'];if(!siblings.every(h=>dist(EXPECT.hue,h)>70))errors.push('hue-distance');if(!/viewBox="0 0 640 400"/.test(artText)||!/#3B6FD4/.test(artText)||/<script|https?:/i.test(artText))errors.push('art-contract');return errors}
const doc=JSON.parse(fs.readFileSync(FILE,'utf8')),art=fs.readFileSync(ART,'utf8'),errors=validate(doc,art);if(errors.length){console.error('FAIL manifest — '+errors.join(', '));process.exit(1)}
console.log('PASS manifest — 34 entries; Apex Tennis exactly once; 4 Sports entries; art complete');console.log('PASS fields — description/head copy exact; /apextennis/; Physics; #3B6FD4');console.log('PASS hue — distances '+['#2F8F6B','#F2A24A','#7C5CFC'].map(h=>dist(EXPECT.hue,h).toFixed(1)).join('/'));
if(process.argv.includes('--self-test')){const families=[['duplicate',d=>d.games.push({...EXPECT})],['description',d=>d.games.find(x=>x.title===EXPECT.title).desc='rewritten'],['href',d=>d.games.find(x=>x.title===EXPECT.title).href='/Lessons/Apex_Tennis/'],['art',d=>delete d.games.find(x=>x.title===EXPECT.title).art],['hue',d=>d.games.find(x=>x.title===EXPECT.title).hue='#2F8F6B'],['order',d=>{const i=d.games.findIndex(x=>x.title==='Apex Tennis'),x=d.games.splice(i,1)[0],k=d.games.findIndex(x=>x.title==='Apex Kick');d.games.splice(k,0,x)}]];let caught=0;for(const [name,mut] of families){const d=JSON.parse(JSON.stringify(doc));mut(d);if(validate(d,art).length){caught++;console.log('PASS tamper '+name+' rejected')}else console.error('FAIL tamper '+name+' escaped')}if(caught!==families.length)process.exit(1);console.log('ALL '+caught+' MANIFEST MUTATION FAMILIES REJECTED')}
